-- MySQL Script generated by MySQL Workbench
-- Thu Nov 15 12:21:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WETR
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS WETR ;

-- -----------------------------------------------------
-- Schema WETR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS WETR DEFAULT CHARACTER SET utf8 ;
USE WETR ;

-- -----------------------------------------------------
-- Table WETR.Region
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.Region (
  IdRegion INT NOT NULL,
  Name VARCHAR(30) NOT NULL,
  PRIMARY KEY (IdRegion))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.Location
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.Location (
  IdLocation INT NOT NULL,
  Address VARCHAR(45) NOT NULL,
  ZIP VARCHAR(10) NOT NULL,
  Longitude VARCHAR(10) NOT NULL,
  Latitude DECIMAL(9,6) NOT NULL,
  Region INT NULL,
  PRIMARY KEY (IdLocation),
  INDEX RegionKey_idx (Region ASC) VISIBLE,
  CONSTRAINT RegionKey
    FOREIGN KEY (Region)
    REFERENCES WETR.Region (IdRegion)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.Station
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.Station (
  IdStation INT NOT NULL,
  Name VARCHAR(30) NOT NULL,
  Type VARCHAR(45) NOT NULL,
  Location INT NULL,
  PRIMARY KEY (IdStation),
  INDEX LocationKey_idx (Location ASC) VISIBLE,
  CONSTRAINT LocationKey
    FOREIGN KEY (Location)
    REFERENCES WETR.Location (IdLocation)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.Privilege
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.Privilege (
  IdPrivilege INT NOT NULL,
  PRIMARY KEY (IdPrivilege))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.User
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.User (
  IdUser INT NOT NULL,
  Name VARCHAR(30) NOT NULL,
  PassHash CHAR(32) NOT NULL,
  Privilege INT NOT NULL,
  Station INT NOT NULL,
  PRIMARY KEY (IdUser),
  INDEX PrivilegeKey_idx (Privilege ASC) VISIBLE,
  INDEX StationUserKey_idx (Station ASC) VISIBLE,
  CONSTRAINT PrivilegeKey
    FOREIGN KEY (Privilege)
    REFERENCES WETR.Privilege (IdPrivilege)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT StationUserKey
    FOREIGN KEY (Station)
    REFERENCES WETR.Station (IdStation)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.UnitOfMeasurement
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.UnitOfMeasurement (
  IdUnit INT NOT NULL AUTO_INCREMENT,
  Unit VARCHAR(45) NOT NULL,
  PRIMARY KEY (IdUnit),
  UNIQUE INDEX Unit_UNIQUE (Unit ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.Measurement
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.Measurement (
  IdMeasurement INT NOT NULL,
  AirTemperature DECIMAL(5,2) NULL,
  AirPressure DECIMAL(6,2) NULL,
  Precipitation INT NULL,
  Humidity DECIMAL(5,2) NULL,
  WindSpeed DECIMAL(5,2) NULL,
  WindDirection INT NULL,
  Value DECIMAL(10,4) NULL,
  TimeStamp DATETIME NULL,
  MeasurementUnit INT NULL,
  Station INT NULL,
  PRIMARY KEY (IdMeasurement),
  INDEX MUnit_idx (MeasurementUnit ASC) VISIBLE,
  INDEX StationMKey_idx (Station ASC) VISIBLE,
  CONSTRAINT MUnit
    FOREIGN KEY (MeasurementUnit)
    REFERENCES WETR.UnitOfMeasurement (IdUnit)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT StationMKey
    FOREIGN KEY (Station)
    REFERENCES WETR.Station (IdStation)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.Community
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.Community (
  IdRegion INT NOT NULL,
  INDEX fk_Community_Region1_idx (IdRegion ASC) VISIBLE,
  PRIMARY KEY (IdRegion),
  CONSTRAINT fk_Community_Region1
    FOREIGN KEY (IdRegion)
    REFERENCES WETR.Region (IdRegion)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.District
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.District (
  IdRegion INT NOT NULL,
  INDEX fk_District_Region1_idx (IdRegion ASC) VISIBLE,
  PRIMARY KEY (IdRegion),
  CONSTRAINT fk_District_Region1
    FOREIGN KEY (IdRegion)
    REFERENCES WETR.Region (IdRegion)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WETR.Province
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS WETR.Province (
  IdRegion INT NOT NULL,
  INDEX fk_Province_Region1_idx (IdRegion ASC) VISIBLE,
  PRIMARY KEY (IdRegion),
  CONSTRAINT fk_Province_Region1
    FOREIGN KEY (IdRegion)
    REFERENCES WETR.Region (IdRegion)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table WETR.UnitOfMeasurement
-- -----------------------------------------------------
START TRANSACTION;
USE WETR;
INSERT INTO WETR.UnitOfMeasurement (IdUnit, Unit) VALUES (1, 'Celsius');
INSERT INTO WETR.UnitOfMeasurement (IdUnit, Unit) VALUES (2, 'Pascal');
INSERT INTO WETR.UnitOfMeasurement (IdUnit, Unit) VALUES (3, 'g/m3');
INSERT INTO WETR.UnitOfMeasurement (IdUnit, Unit) VALUES (4, 'km');

COMMIT;

